allow-flight=true
enable-command-block=true
enable-rcon=false
level-name=world
level-type: BIOMESOP
max-tick-time=90000
motd=Server
rcon.password=minecraft
snooper-enabled=false
view-distance=8
white-list=false
